version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
    secrets:
      - db_user
      - db_password
    environment:
      MYSQL_HOST: db
      MYSQL_DATABASE: notesdb
    restart: always

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_password
      MYSQL_USER_FILE: /run/secrets/db_user
      MYSQL_PASSWORD_FILE: /run/secrets/db_password
      MYSQL_DATABASE: notesdb
    secrets:
      - db_user
      - db_password
    volumes:
      - db_data:/var/lib/mysql
    restart: always

secrets:
  db_user:
    file: ./secrets/db_user.txt
  db_password:
    file: ./secrets/db_password.txt

volumes:
  db_data:
